// Errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


// Loading
export const LOADING = 'LOADING';
export const REMOVE_LOADING = 'REMOVE_LOADING';

export const CLEAR_SUCCESS_MESSAGE = 'CLEAR_SUCCESS_MESSAGE';
export const GET_SUCCESS_MESSAGE = 'GET_SUCCESS_MESSAGE';

// Auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_CREATED = 'USER_CREATED';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_REMAINING_BALANCE = 'UPDATE_REMAINING_BALANCE';

// Transactions
export const SET_USER_TRANSACTIONS = 'SET_USER_TRANSACTIONS';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const LOAD_FUNDS = 'LOAD_FUNDS';